config/routes.rb
# For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
Rails.application.routes.draw do
  # GET /about
  # get "about", to: "about#index"
  get "about-us", to: "about#index", as: :about

  # account sign_up
  get "sign_up", to: "registrations#new"
  post "sign_up", to: "registrations#create"

  # account sign_in
  get "sign_in", to: "sessions#new"
  post "sign_in", to: "sessions#create"

  # account sign_out
  delete "logout", to: "sessions#destroy"

  # update profile
  get "profile", to: "profile#edit"
  patch "profile", to: "profile#update"

  # reset password
  get "password/reset", to: "password_reset#new"
  post "password/reset", to: "password_reset#create"

  # edit reset password
  get "password/reset/edit", to: "password_reset#edit"
  patch "password/reset/edit", to: "password_reset#update"

  get "/auth/twitter/callback", to: "omniauth_callbacks#twitter"

  resources :twitter_accounts
  resources :tweets

  root to: "main#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/current.rb
class Current < ActiveSupport::CurrentAttributes
  attribute :user
end

app/models/tweet.rb
class Tweet < ApplicationRecord
  belongs_to :user
  belongs_to :twitter_account
end

app/models/twitter_account.rb
class TwitterAccount < ApplicationRecord
  belongs_to :user

  validates :username, uniqueness: true
end

app/models/user.rb
# email:string
# password_digest:string
#
# password:string virtual
# password_confirmation:string virtual

class User < ApplicationRecord
  has_many :twitter_accounts
  has_many :tweets
  has_secure_password

  validates :email, presence: true, uniqueness: true, format: { with: /\A[^@\s]+@[^@\s]+\z/, message: "must be a valid email address"}
end

app/controllers/about_controller.rb
class AboutController < ApplicationController
  def index
  end 
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :set_current_user
  
  def set_current_user
    if session[:user_id]
      Current.user = User.find_by(id: session[:user_id])
    end    
  end

  def require_user_logged_in!
    redirect_to sign_in_path, alert: "You must be signed in to do that!!" if Current.user.nil?
  end
end

app/controllers/main_controller.rb
class MainController < ApplicationController
  def index
  end
end

app/controllers/omniauth_callbacks_controller.rb
class OmniauthCallbacksController < ApplicationController
  def twitter
    twitter_account = Current.user.twitter_accounts.where(username: auth.info.nickname).first_or_initialize
    twitter_account.update(
      name: auth.info.name,
      image: auth.info.image,
      token: auth.credentials.token,
      secret: auth.credentials.secret,
    )
    redirect_to twitter_accounts_path, notice: "Successfully connected with your account"
  end

  def auth
    request.env['omniauth.auth']
  end
end

app/controllers/password_reset_controller.rb
class PasswordResetController < ApplicationController
  def new
  end

  def create
    @user = User.find_by(email: params[:email])

    if @user.present?
      PasswordMailer.with(user: @user).reset.deliver_later
    end

    redirect_to root_path, notice: "If an account with that email was found, We have sent an email to reset your password."
  end

  def edit
    @user = User.find_signed!(params[:token], purpose: "password_reset")

    rescue ActiveSupport::MessageVerifier::InvalidSignature
      redirect_to sign_in_path, alert: "Your token has expired, please try again!"
    
  end

  def update
    @user = User.find_signed!(params[:token], purpose: "password_reset")
    if @user.update(password_params)
      redirect_to sign_in_path, notice: "Your password has changed successfully, please login again."
    else
      render :edit
    end
  end


  private

  def password_params
    params.require(:user).permit(:password, :password_confirmation)
  end
end

app/controllers/profile_controller.rb
class ProfileController < ApplicationController
  before_action :require_user_logged_in!

  def edit    
  end

  def update
    if Current.user.authenticate(params[:user][:old_password])
      if Current.user.update(password_params)
        redirect_to root_path, notice: "Password Updated!"
      else
        render :edit
      end
    else
      flash[:alert] = "old password is not correct"
      render :edit
    end
  end

  private

  def password_params
    params.require(:user).permit(:password, :password_confirmation)
  end

end

app/controllers/registrations_controller.rb
class RegistrationsController < ApplicationController

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to root_path, notice: "Successfully created account!"
    else
      render :new
    end
  end

  private

  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation)
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:email])

    if user.present? && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to root_path, notice: "Logged In Successfully"
    else
      flash[:alert] = "Invalid email or password"
      render :new
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path, notice: "Logged out"
  end
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  before_action :require_user_logged_in!

  def index
    @tweets = Current.user.tweets
  end

  def new
    @tweet = Tweet.new
  end
end

app/controllers/twitter_accounts_controller.rb
class TwitterAccountsController < ApplicationController
  before_action :require_user_logged_in!
  before_action :set_twitter_account, only: [:destroy]

  def index
    @twitter_accounts = Current.user.twitter_accounts
  end

  def destroy
    @twitter_account.destroy
    redirect_to twitter_accounts_path, notice: "Successfully discounter @#{@twitter_account.username}"
  end

  private

  def set_twitter_account
    @twitter_account = Current.user.twitter_accounts.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/about/index.html.erb
<h1>About US</h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ScheduledTweets</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render partial: "shared/navbar" %>
    <div class="container">
    <%= render partial: "shared/flash" %>
      <%= yield %>  
    </div>
  </body>
</html>

app/views/main/index.html.erb
<div class="d-flex justify-content-center align-items-center">
  <h1>
    Welcome Home!
  </h1>
</div>

app/views/password_reset/edit.html.erb
<div class="d-flex flex-column justify-content-center my-5">
  <h1 class="mx-auto">Reset Your Password</h1>

  <%= form_with model: @user, class: "d-flex flex-column align-items-center", url: password_reset_edit_path(token: params[:token]) do |form| %>
    <% if form.object.errors.any? %>
      <div class="alert alert-danger">
        <% form.object.errors.full_messages.each do |message| %>
          <div>
            <%= message %>
          </div>
        <% end %>
      </div>
    <% end %>
    <div class="mb-3">
      <%= form.label :password, class: "form-label d-block" %>
      <%= form.password_field :password, placeholder: "password" %>
    </div>
    <div class="mb-3">
      <%= form.label :password_confirmation, class: "form-label d-block" %>
      <%= form.password_field :password_confirmation, placeholder: "confirm password" %>
    </div>
    <div class="mb-3">
      <%= form.submit "Reset Password", class: "btn btn-primary"%>
    </div>
  <% end %>
</div>

app/views/password_reset/new.html.erb
<div class="d-flex flex-column justify-content-center my-5">
  <h1 class="mx-auto">Reset Password</h1>

  <%= form_with class: "d-flex flex-column align-items-center", url: password_reset_path do |form| %>
    <div class="mb-3">
      <%= form.label :email, class: "form-label d-block" %>
      <%= form.text_field :email, placeholder: "john@example.com" %>
    </div>
    <div class="mb-3">
      <%= form.submit "Reset Password", class: "btn btn-primary"%>
    </div>
  <% end %>
</div>

app/views/shared/_flash.html.erb
<% if flash[:notice] %>
  <div class="alert alert-primary" role="alert">
    <%= flash[:notice] %>
  </div>
<% end %>
<% if flash[:alert] %>
  <div class="alert alert-warning" role="alert">
  <%= flash[:alert] %>
</div>
<% end %>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg bg-body-tertiary">
  <div class="container-fluid">
    <%= link_to "Navbar", root_path, class: "navbar-brand" %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <%= link_to "Tweets", tweets_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Twitter Accounts", twitter_accounts_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "About", about_path, class: "nav-link" %>
        </li>
        <% if Current.user %>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              <%= Current.user.email%>
            </a>
            <ul class="dropdown-menu">
              <li>
                <%= link_to "Profile", profile_path, class: "dropdown-item" %>
              </li>
              <li>
                <%= button_to "Logout", logout_path, method: :delete, class: "dropdown-item" %>
              </li>
            </ul>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "SignUp", sign_up_path, class: "nav-link" %>
          </li> 
        <% end %>
      </ul>
      <form class="d-flex" role="search">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav>

app/views/tweets/index.html.erb
<div class="d-flex justify-content-between align-items-center">
  <h1>
    Tweets
  </h1>

  <% if Current.user.twitter_accounts.any? %>
    <%= link_to "Scheduled a Tweet", new_tweet_path, class: "btn btn-primary" %>
  <% end %>
</div>

  <% if Current.user.twitter_accounts.none? %>
    <%= button_to "Connect Twitter", "/auth/twitter", method: :post, class: "btn btn-primary mx-auto" %>
  <% end %>

<% @tweets.each do |tweet| %>
  <div class="d-flex align-items-center mb-4">
    <div class="me-4">
      <%= tweet.body %>
    </div>

    <%= button_to "Disconnect", tweet, method: :delete, data: { confirm: "Are you sure?" }, class: "btn btn-primary" %>
  </div>
<% end %>

app/views/tweets/new.html.erb
<h1>Schedule A Tweet</h1>

<%= form_with model: @tweet do |form| %>
  <div>
    <%= form.label :twitter_account_id %>
    <%= form.collection_select :twitter_account_id, Current.user.twitter_accounts, :id, :username, {}, {class: "form-control"} %>
    <%= button_to "Connect your Twitter Twitter", "/auth/twitter", method: :post, class: "btn btn-primary my-2 ms-auto" %>
  </div>

  <div class="mb-3">
    <%= form.label :body %>
    <%= form.text_area :body, class: "form-control" %>
  </div>

  <div class="mb-3">
    <%= form.label :publish_at %>
    <%= form.datetime_select :publish_at, class: "form-control" %>
  </div>

  <%= form.button "Schedule", class: "btn btn-primary"%>
<% end %>

app/views/twitter_accounts/index.html.erb
<div class="d-flex justify-content-between align-items-center">
  <h1>
    Twitter Accounts
  </h1>
  <%
=begin%>
 omniAuth doesn't support link_to for a post method, need to use button_to for that 
<%
=end%>
  <%= button_to "Connect Twitter", "/auth/twitter", method: :post, class: "btn btn-primary mx-auto" %>
</div>

<% @twitter_accounts.each do |twitter_account| %>
  <div class="d-flex align-items-center mb-4">
    <div class="me-4">
      <%= image_tag twitter_account.image, class: "rounded-circle" %>
      <%= link_to "#{twitter_account.username}", "https://twitter.com/#{twitter_account.username}", target: :_blank %>
    </div>

    <%= button_to "Disconnect", twitter_account, method: :delete, data: { confirm: "Are you sure?" }, class: "btn btn-primary" %>
  </div>
<% end %>